### PR TITLE
Ml display update

### PR DESCRIPTION
**Pull request by mjleavell**
#12 
@rousell I had to do some weird stuff to get the images displayed from the weatherbit api. I created the weatherObject prop because it was the only way i could get the images to display. If i just used weatherData, I got all sorts of weird errors from the api. Let me know what you think.

### CODE REVIEW

**Comment by rousell** [comment]
Small fix - in Auth.js, you have a `console.err()` that should be a `console.error()`

**Comment by mjleavell** [comment]
@rousell should be good now

**Comment by rousell** [comment]
@mjleavell  Yep - so you should be able to explicitly choose which data that you want in your weather object:
```
        this.setState({
          currentWeather: {
            weatherIcon: weatherData.weather.icon,
            weatherDescription: weatherData.weather.description,
            city: weatherData.city_name,
          },
        });
```
It would probably include something like that, plus the additional fields that you use. That should simplify it so that you only need one object to hold the current weather. 

Another thing you may consider doing is to only pass your firebase information (city, state, etc) to your WeatherCurrent component, and then making the Api Call to the weatherbit api from there. This would make the component more reusable, since it would then only require the information needed to be passed in enough data into props to call the api. You can use your best judgement on that -- either way works for the purposes of this application

**Comment by mjleavell** [comment]
@rousell oh my gosh that makes so much sense about the currentWeather object! I made that change. 

As far as the firebase information, I think I did what you suggested. I moved my getCurrentWeather firebase call and weatherbit api call to my WeatherCurrent component. I agree that doing so makes the component more reusable.

**Comment by rousell** [comment]
@mjleavell This looks great! 👍 merging

**Pull request merged**
