### PR TITLE
reading weather from firebase and displaying

### PR DESCRIPTION
**Pull request by mjleavell**
#9 

@rousell this PR is ready. It is pretty basic. All I am doing is displaying the city and state for the weather locations that have my UID.

### CODE REVIEW

**Comment by rousell** [comment]
Hi @mjleavell - good job figuring out a way to reliably pass props to the component in a route page! Nicely done. I think that if you wanted to pass your uid down from your App state into your component, that would be a good use of this code. 

That being said, my main suggestion here would be for you to move your weather state into your Weather page component. The reason for this is that none of the other places in a complete nutshell application would need the weather information, so that data does not need to be held in state at the App level. Keeping weather in App will end up bloating out that component file, since all the functions needed to change your weather state would be located in App.js. 

Let me know if that makes sense // if you have any questions.

**Comment by mjleavell** [comment]
@rousell that makes so much sense! I made the necessary changes. Let me know if I missed anything else. Thank you!

**Comment by mjleavell** [comment]
@rousell I made all the changes you requested, but I'm not sure I "resolved" them properly on github.

**Comment by rousell** [comment]
@mjleavell looks great! 👍 merging now

**Pull request merged**
